name: analyzed_demo_plugin_loader
version: 1.0.0-dev
description: 这是插件使用的依赖关系
environment:
  sdk: ">=2.8.1 <3.0.0"
dependencies:
  analyzer_plugin_demo: ^1.0.0

dependency_overrides:
  analyzer_plugin_demo:
    path: /Users/fd/lyProjects/samples/dart_demos/pub/analyzer_plugin_demo_loader

  #  还支持覆盖操作
# === vvv REMOVE WHEN PUBLISHING vvv ===
#dependency_overrides:
#  angular_analyzer_plugin:
#      path: ../../../angular_analyzer_plugin
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===